import type { FieldValue, LineItemRowState } from '../../types';
import { ROW_ID_KEY } from './lineItems';

const areFieldValuesEqual = (a: FieldValue, b: FieldValue): boolean => {
  if (a === b) return true;
  if (Array.isArray(a) || Array.isArray(b)) {
    const arrA = Array.isArray(a) ? a : [];
    const arrB = Array.isArray(b) ? b : [];
    if (arrA.length !== arrB.length) return false;
    for (let i = 0; i < arrA.length; i += 1) {
      if (arrA[i] !== arrB[i]) return false;
    }
    return true;
  }
  if (typeof a === 'object' || typeof b === 'object') {
    try {
      return JSON.stringify(a) === JSON.stringify(b);
    } catch {
      return false;
    }
  }
  return false;
};

const areValueMapsEqual = (a: Record<string, FieldValue>, b: Record<string, FieldValue>): boolean => {
  if (a === b) return true;
  const keys = Array.from(new Set([...Object.keys(a || {}), ...Object.keys(b || {})]));
  for (const key of keys) {
    if (!areFieldValuesEqual((a as any)[key], (b as any)[key])) return false;
  }
  return true;
};

const areLineItemRowsEqual = (a: LineItemRowState, b: LineItemRowState): boolean =>
  a.id === b.id &&
  a.parentId === b.parentId &&
  a.parentGroupId === b.parentGroupId &&
  a.autoGenerated === b.autoGenerated &&
  a.effectContextId === b.effectContextId &&
  areValueMapsEqual((a.values || {}) as Record<string, FieldValue>, (b.values || {}) as Record<string, FieldValue>);

export const buildSelectionEffectLineItemUpsert = (args: {
  rows: LineItemRowState[];
  existingIdxs: number[];
  keepIdx: number;
  presetValues: Record<string, FieldValue>;
  parentRowId?: string;
  parentGroupId?: string;
  autoGenerated?: boolean;
  effectContextId?: string;
}): { nextRows: LineItemRowState[]; changed: boolean } => {
  const baseRow = args.rows[args.keepIdx];
  const mergedValues: Record<string, FieldValue> = {
    ...((baseRow?.values || {}) as Record<string, FieldValue>),
    ...args.presetValues
  };
  if (!mergedValues[ROW_ID_KEY]) mergedValues[ROW_ID_KEY] = baseRow.id;

  const nextRow: LineItemRowState = {
    ...baseRow,
    values: mergedValues,
    parentId: args.parentRowId,
    parentGroupId: args.parentGroupId,
    autoGenerated: args.autoGenerated === undefined ? baseRow.autoGenerated : args.autoGenerated,
    effectContextId: args.effectContextId === undefined ? baseRow.effectContextId : args.effectContextId
  };
  const nextRows = args.rows
    .map((row, idx) => (idx === args.keepIdx ? nextRow : row))
    .filter((_, idx) => !args.existingIdxs.includes(idx) || idx === args.keepIdx);

  return {
    nextRows,
    changed: args.existingIdxs.length > 1 || !areLineItemRowsEqual(baseRow, nextRow)
  };
};
