import {
  appendAdminQuery,
  appendLandingSpecialItems,
  buildBundledLandingCatalog,
  buildLandingCatalogLayout,
  filterNavigableLandingItems,
  pickLandingLogoUrl,
  pickLandingLogoUrlByFormKey,
  resolveLandingCatalogItems,
  resolveLandingLogoUrl,
  resolveLandingHeaderTitle
} from '../../src/web/react/landing/model';
import type { LandingPageConfig } from '../../src/config/landingPageTypes';

const landingConfigFixture: LandingPageConfig = {
  brandName: 'Community Kitchen',
  heroTitle: 'Welcome to the Community Kitchen',
  heroDescription: 'Select an app below to begin managing operations.',
  appHeader: {
    logoFormKey: 'Config: Meal Production'
  },
  copy: {
    refreshLabel: 'Refresh',
    loadingAppsLabel: 'Loading apps...',
    emptyPrimaryAppsLabel: 'No primary apps were found.',
    pendingNavigationTitle: 'Please wait',
    pendingNavigationMessage: 'Opening the selected app...',
    openAppLabel: 'Go to app',
    primarySectionTitle: 'Apps for cooks',
    adminSectionTitle: 'Administrator apps',
    adminSectionNote: '',
    overflowTitle: 'More Admin Forms',
    overflowShowLabel: 'Show forms',
    overflowHideLabel: 'Hide forms',
    overflowDescriptionSingular: 'Open the remaining admin form.',
    overflowDescriptionPlural: 'Open the remaining {count} admin forms and internal tools.'
  },
  apps: [
    {
      formKey: 'Config: Checklist',
      section: 'primary',
      order: 10,
      illustration: 'checks',
      imageUrl: 'data:image/jpeg;base64,checks',
      title: 'Storage & cleaning checks',
      description: 'Conduct cleaning inspections and check food storage.'
    },
    {
      formKey: 'Config: Meal Production',
      section: 'primary',
      order: 20,
      illustration: 'meal',
      imageUrl: 'data:image/jpeg;base64,meal',
      title: 'Meal Production',
      description: 'Plan, produce, and manage daily meals.'
    },
    {
      formKey: 'Config: Distributor',
      section: 'admin',
      order: 10,
      illustration: 'customers',
      imageUrl: 'data:image/jpeg;base64,customers',
      title: 'Customer Management',
      description: 'Manage and communicate with customers.'
    },
    {
      formKey: 'Config: Ingredients Management',
      section: 'admin',
      order: 20,
      illustration: 'ingredients',
      imageUrl: 'data:image/jpeg;base64,ingredients',
      title: 'Ingredient Management',
      description: 'Track inventory of ingredients and supplies.'
    },
    {
      formKey: 'Config: Recipes',
      section: 'admin',
      order: 30,
      illustration: 'recipes',
      imageUrl: 'data:image/jpeg;base64,recipes',
      title: 'Recipe Management',
      description: 'Create, edit, and organize cooking recipes.'
    },
    {
      formKey: 'Config: Leftover Inventory',
      section: 'overflow',
      order: 40,
      illustration: 'admin',
      title: 'Leftover Inventory',
      description: 'Track reusable leftovers and their remaining availability.'
    },
    {
      formKey: 'Config: Inventory Reservation Ledger',
      section: 'overflow',
      order: 50,
      illustration: 'admin',
      title: 'Inventory Reservation Ledger',
      description: 'Review internal inventory reservations generated by operations.'
    }
  ]
};

describe('landing model helpers', () => {
  test('appendAdminQuery appends admin=true without disturbing hash fragments', () => {
    expect(appendAdminQuery('https://example.test/app?form=A#section', true)).toBe(
      'https://example.test/app?form=A&admin=true#section'
    );
  });

  test('pickLandingLogoUrl returns the most common configured logo', () => {
    expect(
      pickLandingLogoUrl([
        { formKey: 'a', title: 'A', targetUrl: 'https://example.test/a', logoUrl: 'https://img.test/shared.png' },
        { formKey: 'b', title: 'B', targetUrl: 'https://example.test/b', logoUrl: 'https://img.test/other.png' },
        { formKey: 'c', title: 'C', targetUrl: 'https://example.test/c', logoUrl: 'https://img.test/shared.png' }
      ])
    ).toBe('https://img.test/shared.png');
  });

  test('pickLandingLogoUrlByFormKey returns the requested form logo when present', () => {
    const items = [
      { formKey: 'Config: Checklist', title: 'A', targetUrl: 'https://example.test/a', logoUrl: 'https://img.test/checks.png' },
      { formKey: 'Config: Meal Production', title: 'B', targetUrl: 'https://example.test/b', logoUrl: 'https://img.test/meal.png' }
    ] as any;

    expect(pickLandingLogoUrlByFormKey(items, 'Config: Meal Production')).toBe('https://img.test/meal.png');
    expect(pickLandingLogoUrlByFormKey(items, 'Config: Missing')).toBeUndefined();
  });

  test('resolveLandingLogoUrl prefers explicit landing config, then the configured form logo, and finally catalog branding', () => {
    const items = [
      { formKey: 'Config: Checklist', title: 'A', targetUrl: 'https://example.test/a', logoUrl: 'https://img.test/shared.png' },
      { formKey: 'Config: Meal Production', title: 'B', targetUrl: 'https://example.test/b', logoUrl: 'https://img.test/meal.png' },
      { formKey: 'Config: Recipes', title: 'C', targetUrl: 'https://example.test/c', logoUrl: 'https://img.test/shared.png' }
    ] as any;

    expect(resolveLandingLogoUrl('https://img.test/configured.png', 'Config: Meal Production', items)).toBe('https://img.test/configured.png');
    expect(resolveLandingLogoUrl('', 'Config: Meal Production', items)).toBe('https://img.test/meal.png');
    expect(resolveLandingLogoUrl('', '', items)).toBe('https://img.test/shared.png');
  });

  test('resolveLandingHeaderTitle prefers explicit landing config and otherwise falls back to document title', () => {
    expect(resolveLandingHeaderTitle('', '')).toBe('Community Kitchen');
    expect(resolveLandingHeaderTitle('Landing', '')).toBe('Landing');
    expect(resolveLandingHeaderTitle('Landing', 'Community Kitchen')).toBe('Community Kitchen');
  });

  test('buildBundledLandingCatalog derives launcher items from embedded configs', () => {
    const items = buildBundledLandingCatalog([
      {
        formKey: 'Config: Meal Production',
        generatedAt: '2026-04-04T00:00:00.000Z',
        form: {
          title: 'Meal Production',
          configSheet: 'Config: Meal Production',
          description: 'Produce meals',
          appUrl: 'https://example.test/exec?form=Config%3A%20Meal%20Production',
          appHeader: {
            logoUrl: 'https://img.test/logo.png'
          }
        } as any,
        questions: [],
        dedupRules: [],
        definition: {} as any,
        validationErrors: []
      },
      {
        formKey: 'Config: Checklist',
        generatedAt: '2026-04-04T00:00:00.000Z',
        form: {
          title: 'Checklist',
          configSheet: 'Config: Checklist',
          appUrl: 'https://example.test/exec?form=Config%3A%20Checklist'
        } as any,
        questions: [],
        dedupRules: [],
        definition: {} as any,
        validationErrors: []
      }
    ] as any);

    expect(items).toEqual([
      {
        formKey: 'Config: Checklist',
        title: 'Checklist',
        description: undefined,
        targetUrl: 'https://example.test/exec?form=Config%3A%20Checklist',
        logoUrl: undefined
      },
      {
        formKey: 'Config: Meal Production',
        title: 'Meal Production',
        description: 'Produce meals',
        targetUrl: 'https://example.test/exec?form=Config%3A%20Meal%20Production',
        logoUrl: 'https://img.test/logo.png'
      }
    ]);
  });

  test('buildBundledLandingCatalog leaves targetUrl empty when only runtime catalog can resolve it', () => {
    const items = buildBundledLandingCatalog([
      {
        formKey: 'Config: Inventory',
        generatedAt: '2026-04-04T00:00:00.000Z',
        form: {
          title: 'Inventory',
          configSheet: 'Config: Inventory',
          formId: 'ignored-runtime-only-id'
        } as any,
        questions: [],
        dedupRules: [],
        definition: {} as any,
        validationErrors: []
      }
    ] as any);

    expect(items).toEqual([
      {
        formKey: 'Config: Inventory',
        title: 'Inventory',
        description: undefined,
        targetUrl: undefined,
        logoUrl: undefined
      }
    ]);
  });

  test('filterNavigableLandingItems keeps only resolvable targets and applies admin query', () => {
    expect(
      filterNavigableLandingItems(
        [
          { formKey: 'a', title: 'Zeta', targetUrl: 'https://example.test/zeta' },
          { formKey: 'b', title: 'Alpha', targetUrl: '' },
          { formKey: 'c', title: 'Beta', targetUrl: 'https://example.test/beta?x=1' }
        ] as any,
        true
      )
    ).toEqual([
      {
        formKey: 'c',
        title: 'Beta',
        targetUrl: 'https://example.test/beta?x=1&admin=true'
      },
      {
        formKey: 'a',
        title: 'Zeta',
        targetUrl: 'https://example.test/zeta?admin=true'
      }
    ]);
  });

  test('resolveLandingCatalogItems waits for runtime targets before exposing landing navigation', () => {
    expect(resolveLandingCatalogItems([], true)).toEqual([]);
  });

  test('resolveLandingCatalogItems prefers the runtime catalog when it is available', () => {
    const runtimeItems = [
      { formKey: 'Config: Meal Production', title: 'Meal Production', targetUrl: 'https://example.test/runtime' },
      { formKey: 'Config: Checklist', title: 'Checklist', targetUrl: '' }
    ] as any;

    expect(resolveLandingCatalogItems(runtimeItems, true)).toEqual([
      {
        formKey: 'Config: Meal Production',
        title: 'Meal Production',
        targetUrl: 'https://example.test/runtime?admin=true'
      }
    ]);
  });

  test('buildLandingCatalogLayout maps the mockup copy and groups overflow admin forms', () => {
    expect(
      buildLandingCatalogLayout(
        [
          { formKey: 'Config: Inventory Reservation Ledger', title: 'Inventory Reservation Ledger', targetUrl: 'https://example.test/ledger' },
          { formKey: 'Config: Checklist', title: 'Storage & cleaning checks', targetUrl: 'https://example.test/checks' },
          { formKey: 'Config: Distributor', title: 'Distributors', targetUrl: 'https://example.test/distributors' },
          { formKey: 'Config: Meal Production', title: 'Meal Production', targetUrl: 'https://example.test/meal' },
          { formKey: 'Config: Ingredients Management', title: 'Ingredients Management', targetUrl: 'https://example.test/ingredients' },
          { formKey: 'Config: Recipes', title: 'Recipe Management', targetUrl: 'https://example.test/recipes' },
          { formKey: 'Config: Leftover Inventory', title: 'Leftover Inventory', targetUrl: 'https://example.test/leftovers' }
        ] as any,
        true,
        landingConfigFixture
      )
    ).toEqual({
      primaryApps: [
        {
          formKey: 'Config: Checklist',
          title: 'Storage & cleaning checks',
          targetUrl: 'https://example.test/checks',
          displayTitle: 'Storage & cleaning checks',
          displayDescription: 'Conduct cleaning inspections and check food storage.',
          illustration: 'checks',
          imageUrl: 'data:image/jpeg;base64,checks'
        },
        {
          formKey: 'Config: Meal Production',
          title: 'Meal Production',
          targetUrl: 'https://example.test/meal',
          displayTitle: 'Meal Production',
          displayDescription: 'Plan, produce, and manage daily meals.',
          illustration: 'meal',
          imageUrl: 'data:image/jpeg;base64,meal'
        }
      ],
      adminApps: [
        {
          formKey: 'Config: Distributor',
          title: 'Distributors',
          targetUrl: 'https://example.test/distributors',
          displayTitle: 'Customer Management',
          displayDescription: 'Manage and communicate with customers.',
          illustration: 'customers',
          imageUrl: 'data:image/jpeg;base64,customers'
        },
        {
          formKey: 'Config: Ingredients Management',
          title: 'Ingredients Management',
          targetUrl: 'https://example.test/ingredients',
          displayTitle: 'Ingredient Management',
          displayDescription: 'Track inventory of ingredients and supplies.',
          illustration: 'ingredients',
          imageUrl: 'data:image/jpeg;base64,ingredients'
        },
        {
          formKey: 'Config: Recipes',
          title: 'Recipe Management',
          targetUrl: 'https://example.test/recipes',
          displayTitle: 'Recipe Management',
          displayDescription: 'Create, edit, and organize cooking recipes.',
          illustration: 'recipes',
          imageUrl: 'data:image/jpeg;base64,recipes'
        }
      ],
      overflowAdminApps: [
        {
          formKey: 'Config: Leftover Inventory',
          title: 'Leftover Inventory',
          targetUrl: 'https://example.test/leftovers',
          displayTitle: 'Leftover Inventory',
          displayDescription: 'Track reusable leftovers and their remaining availability.',
          illustration: 'admin',
          imageUrl: undefined
        },
        {
          formKey: 'Config: Inventory Reservation Ledger',
          title: 'Inventory Reservation Ledger',
          targetUrl: 'https://example.test/ledger',
          displayTitle: 'Inventory Reservation Ledger',
          displayDescription: 'Review internal inventory reservations generated by operations.',
          illustration: 'admin',
          imageUrl: undefined
        }
      ]
    });
  });

  test('buildLandingCatalogLayout hides admin apps when admin mode is off', () => {
    expect(
      buildLandingCatalogLayout(
        [
          { formKey: 'Config: Checklist', title: 'Storage & cleaning checks', targetUrl: 'https://example.test/checks' },
          { formKey: 'Config: Distributor', title: 'Distributors', targetUrl: 'https://example.test/distributors' },
          { formKey: 'Config: Leftover Inventory', title: 'Leftover Inventory', targetUrl: 'https://example.test/leftovers' }
        ] as any,
        false,
        landingConfigFixture
      )
    ).toEqual({
      primaryApps: [
        {
          formKey: 'Config: Checklist',
          title: 'Storage & cleaning checks',
          targetUrl: 'https://example.test/checks',
          displayTitle: 'Storage & cleaning checks',
          displayDescription: 'Conduct cleaning inspections and check food storage.',
          illustration: 'checks',
          imageUrl: 'data:image/jpeg;base64,checks'
        }
      ],
      adminApps: [],
      overflowAdminApps: []
    });
  });

  test('buildLandingCatalogLayout uses the provided config instead of hardcoded landing copy', () => {
    const customConfig: LandingPageConfig = {
      ...landingConfigFixture,
      apps: [
        {
          formKey: 'Config: Checklist',
          section: 'primary',
          order: 10,
          illustration: 'checks',
          imageUrl: 'data:image/jpeg;base64,custom',
          title: 'Daily sanitation',
          description: 'Run the custom checklist copy from config.'
        }
      ]
    };

    expect(buildLandingCatalogLayout([{ formKey: 'Config: Checklist', title: 'Checklist', targetUrl: 'https://example.test/checks' }] as any, true, customConfig))
      .toEqual({
        primaryApps: [
          {
            formKey: 'Config: Checklist',
            title: 'Checklist',
            targetUrl: 'https://example.test/checks',
            displayTitle: 'Daily sanitation',
            displayDescription: 'Run the custom checklist copy from config.',
            illustration: 'checks',
            imageUrl: 'data:image/jpeg;base64,custom'
          }
        ],
        adminApps: [],
        overflowAdminApps: []
      });
  });

  test('appendLandingSpecialItems merges special cards into the configured order', () => {
    const layout = buildLandingCatalogLayout(
      [
        { formKey: 'Config: Checklist', title: 'Checklist', targetUrl: 'https://example.test/checks' },
        { formKey: 'Config: Distributor', title: 'Distributors', targetUrl: 'https://example.test/distributors' },
        { formKey: 'Config: Ingredients Management', title: 'Ingredients Management', targetUrl: 'https://example.test/ingredients' }
      ] as any,
      true,
      landingConfigFixture
    );

    expect(
      appendLandingSpecialItems(layout, true, [
        {
          id: '__analytics__',
          section: 'admin',
          order: 15,
          illustration: 'analytics',
          targetUrl: 'https://example.test/analytics',
          title: 'Reports',
          description: 'Send operational reports by email.',
          imageUrl: 'data:image/jpeg;base64,analytics'
        }
      ])
    ).toEqual({
      primaryApps: [
        {
          formKey: 'Config: Checklist',
          title: 'Checklist',
          targetUrl: 'https://example.test/checks',
          displayTitle: 'Storage & cleaning checks',
          displayDescription: 'Conduct cleaning inspections and check food storage.',
          illustration: 'checks',
          imageUrl: 'data:image/jpeg;base64,checks'
        }
      ],
      adminApps: [
        {
          formKey: 'Config: Distributor',
          title: 'Distributors',
          targetUrl: 'https://example.test/distributors',
          displayTitle: 'Customer Management',
          displayDescription: 'Manage and communicate with customers.',
          illustration: 'customers',
          imageUrl: 'data:image/jpeg;base64,customers'
        },
        {
          formKey: '__analytics__',
          title: 'Reports',
          targetUrl: 'https://example.test/analytics',
          displayTitle: 'Reports',
          displayDescription: 'Send operational reports by email.',
          illustration: 'analytics',
          imageUrl: 'data:image/jpeg;base64,analytics'
        },
        {
          formKey: 'Config: Ingredients Management',
          title: 'Ingredients Management',
          targetUrl: 'https://example.test/ingredients',
          displayTitle: 'Ingredient Management',
          displayDescription: 'Track inventory of ingredients and supplies.',
          illustration: 'ingredients',
          imageUrl: 'data:image/jpeg;base64,ingredients'
        }
      ],
      overflowAdminApps: []
    });
  });
});
