// Auto-generated by scripts/embed-landing-page-config.js. Do not edit by hand.
// Contains the landing page export embedded from docs/config/exports/staging/landing_page.json without inlined images.

import type { LandingPageConfig } from './landingPageTypes';

export const BUNDLED_LANDING_PAGE_CONFIG_ENV = "staging" as const;
export const BUNDLED_LANDING_PAGE_CONFIG = {
  "brandName": "Community Kitchen",
  "heroTitle": "Welcome to the Community Kitchen",
  "heroDescription": "Select an app below to begin managing operations.",
  "appHeader": {
    "logoFormKey": "Config: Meal Production"
  },
  "copy": {
    "refreshLabel": "Refresh",
    "loadingAppsLabel": "Loading apps...",
    "emptyPrimaryAppsLabel": "No primary apps were found.",
    "pendingNavigationTitle": "Please wait",
    "pendingNavigationMessage": "Opening the selected app...",
    "openAppLabel": "Go to app",
    "primarySectionTitle": "Apps for cooks",
    "adminSectionTitle": "Administrator apps",
    "adminSectionNote": "Reports are available from the dashboard below.",
    "overflowTitle": "More Admin Forms",
    "overflowShowLabel": "Show forms",
    "overflowHideLabel": "Hide forms",
    "overflowDescriptionSingular": "Open the remaining admin form.",
    "overflowDescriptionPlural": "Open the remaining {count} admin forms and internal tools."
  },
  "apps": [
    {
      "formKey": "Config: Checklist",
      "section": "primary",
      "order": 10,
      "illustration": "checks",
      "imagePath": "docs/images/storage-cleaning.png",
      "title": "Storage & cleaning checks",
      "description": "Conduct cleaning inspections and check food storage."
    },
    {
      "formKey": "Config: Meal Production",
      "section": "primary",
      "order": 20,
      "illustration": "meal",
      "imagePath": "docs/images/meal-prod.png",
      "title": "Meal Production",
      "description": "Plan, produce, and manage daily meals."
    },
    {
      "formKey": "Config: Distributor",
      "section": "admin",
      "order": 10,
      "illustration": "customers",
      "imagePath": "docs/images/customers.png",
      "title": "Customer Management",
      "description": "Manage and communicate with customers."
    },
    {
      "formKey": "Config: Ingredients Management",
      "section": "admin",
      "order": 20,
      "illustration": "ingredients",
      "imagePath": "docs/images/ingredients.png",
      "title": "Ingredient Management",
      "description": "Track inventory of ingredients and supplies."
    },
    {
      "formKey": "Config: Recipes",
      "section": "admin",
      "order": 30,
      "illustration": "recipes",
      "imagePath": "docs/images/recipes.png",
      "title": "Recipe Management",
      "description": "Create, edit, and organize cooking recipes."
    },
    {
      "formKey": "Config: Leftover Inventory",
      "section": "overflow",
      "order": 40,
      "illustration": "admin",
      "title": "Leftover Inventory",
      "description": "Track reusable leftovers and their remaining availability."
    },
    {
      "formKey": "Config: Inventory Reservation Ledger",
      "section": "overflow",
      "order": 50,
      "illustration": "admin",
      "title": "Inventory Reservation Ledger",
      "description": "Review internal inventory reservations generated by operations."
    }
  ]
} as LandingPageConfig;
