// Auto-generated by scripts/embed-analytics-page-config.js. Do not edit by hand.
// Contains the analytics page export embedded from docs/config/exports/staging/analytics_page.json without inlined images.

import type { AnalyticsPageConfig } from './analyticsPageTypes';

export const BUNDLED_ANALYTICS_PAGE_CONFIG_ENV = "staging" as const;
export const BUNDLED_ANALYTICS_PAGE_CONFIG = {
  "pageTitle": "Reports",
  "pageDescription": "Send operational reports to the Operations Manager.",
  "appHeader": {
    "logoFormKey": "Config: Meal Production"
  },
  "landingTile": {
    "title": "Reports",
    "description": "Send operational reports by email.",
    "section": "admin",
    "order": 40,
    "imagePath": "docs/images/analytics.png"
  },
  "copy": {
    "loadingLabel": "Loading reports...",
    "emptyLabel": "No reports are available.",
    "backToLandingLabel": "Apps",
    "pendingNavigationTitle": "Please wait",
    "pendingNavigationMessage": "Opening forms..."
  },
  "sections": []
} as AnalyticsPageConfig;
