import { buildLocalizedOptions, computeAllowedOptions, toDependencyValue } from '../../../../core';
import type { FieldValue, LangCode, OptionSet } from '../../../../types';
import type { LineItemState } from '../../../types';
import {
  ROW_SOURCE_AUTO,
  ROW_SOURCE_KEY,
  buildSubgroupKey,
  parseRowSource,
  resolveSubgroupKey
} from '../../../app/lineItems';
import { optionSortFor } from './lineItemPresentation';

const AUTO_CONTEXT_PREFIX = '__autoAddMode__';

export const normalizeAutoAddAnchorKey = (raw: any): string => {
  if (raw === undefined || raw === null) return '';
  if (Array.isArray(raw)) {
    const first = raw[0];
    return first === undefined || first === null ? '' : first.toString().trim();
  }
  return raw.toString().trim();
};

export const resolveAutoAddDependsOnIds = (field: any): string[] => {
  const raw = field?.optionFilter?.dependsOn;
  const ids = Array.isArray(raw) ? raw : raw ? [raw] : [];
  return ids.map((id: any) => (id ?? '').toString().trim()).filter(Boolean);
};

const isValidDependencyValue = (raw: any): boolean => {
  const dep = toDependencyValue(raw as any);
  if (dep === undefined || dep === null) return false;
  if (typeof dep === 'number') return Number.isFinite(dep);
  return dep.toString().trim() !== '';
};

export const resolveAutoAddDesiredRowsAction = (args: {
  groupKey: string;
  anchorField: any;
  dependencyIds: string[];
  getDependencyRaw: (depId: string) => any;
  buildOptionSetForLineField: (field: any, groupKey: string) => OptionSet;
  language: LangCode;
}): { valid: boolean; desired: string[]; depVals: (string | number | null | undefined)[] } => {
  const { groupKey, anchorField, dependencyIds, getDependencyRaw, buildOptionSetForLineField, language } = args;
  const depRawVals = dependencyIds.map(depId => getDependencyRaw(depId));
  const depVals = depRawVals.map(v => toDependencyValue(v as any));
  const valid = dependencyIds.length === 0 || depRawVals.every(isValidDependencyValue);
  if (!valid) return { valid: false, desired: [], depVals };
  const opts = buildOptionSetForLineField(anchorField, groupKey);
  const allowed = computeAllowedOptions(anchorField.optionFilter, opts, depVals);
  const localized = buildLocalizedOptions(opts, allowed, language, { sort: optionSortFor(anchorField) });
  const seen = new Set<string>();
  const desired: string[] = [];
  localized.forEach(opt => {
    const key = (opt?.value ?? '').toString().trim();
    if (!key || seen.has(key)) return;
    seen.add(key);
    desired.push(key);
  });
  return { valid: true, desired, depVals };
};

export const reconcileAutoAddRowsAction = (args: {
  currentRows: any[];
  targetKey: string;
  anchorFieldId: string;
  desired: string[];
  depVals: (string | number | null | undefined)[];
  selectorId?: string;
  selectorValue?: FieldValue;
  createRowId?: (targetKey: string) => string;
}): {
  rows: any[];
  changed: boolean;
  contextId: string;
  desiredCount: number;
} => {
  const { currentRows, targetKey, anchorFieldId, desired, depVals, selectorId, selectorValue } = args;
  const autoPrefix = `${AUTO_CONTEXT_PREFIX}:${targetKey}:`;
  const contextId = `${autoPrefix}${depVals.map(v => (v === undefined || v === null ? '' : v.toString())).join('||')}`;
  const shouldSortRowsByAnchor =
    targetKey === 'MP_MEALS_REQUEST' && anchorFieldId === 'MEAL_TYPE' && Array.isArray(desired) && desired.length > 1;

  const remaining = new Set(desired);

  const nextRows: any[] = [];
  const addedRows: any[] = [];
  currentRows.forEach(row => {
    const isAutoContext =
      (typeof row.effectContextId === 'string' && row.effectContextId.startsWith(autoPrefix)) ||
      parseRowSource((row.values as any)?.[ROW_SOURCE_KEY]) === 'auto';
    if (!isAutoContext) {
      nextRows.push(row);
      return;
    }

    const key = normalizeAutoAddAnchorKey((row.values as any)?.[anchorFieldId]);
    if (!key || !remaining.has(key)) {
      return;
    }
    remaining.delete(key);

    const nextValues: Record<string, FieldValue> = { ...(row.values || {}) };
    let valuesChanged = false;
    if (normalizeAutoAddAnchorKey((nextValues as any)[anchorFieldId]) !== key) {
      nextValues[anchorFieldId] = key;
      valuesChanged = true;
    }
    if (parseRowSource((nextValues as any)[ROW_SOURCE_KEY]) !== 'auto') {
      nextValues[ROW_SOURCE_KEY] = ROW_SOURCE_AUTO;
      valuesChanged = true;
    }
    if (
      selectorId &&
      selectorValue !== undefined &&
      selectorValue !== null &&
      (nextValues as any)[selectorId] === undefined
    ) {
      nextValues[selectorId] = selectorValue;
      valuesChanged = true;
    }

    const metaChanged = row.autoGenerated !== true || row.effectContextId !== contextId;
    if (valuesChanged || metaChanged) {
      nextRows.push({
        ...row,
        values: nextValues,
        autoGenerated: true,
        effectContextId: contextId
      });
    } else {
      nextRows.push(row);
    }
  });

  desired.forEach(key => {
    if (!remaining.has(key)) return;
    remaining.delete(key);
    const nextValues: Record<string, FieldValue> = {
      [anchorFieldId]: key,
      [ROW_SOURCE_KEY]: ROW_SOURCE_AUTO
    };
    if (selectorId && selectorValue !== undefined && selectorValue !== null) {
      nextValues[selectorId] = selectorValue;
    }
    addedRows.unshift({
      id: args.createRowId?.(targetKey) || `${targetKey}_${Math.random().toString(16).slice(2)}`,
      values: nextValues,
      autoGenerated: true,
      effectContextId: contextId
    });
  });

  const combinedRows = addedRows.length ? [...addedRows, ...nextRows] : nextRows;
  const combinedSorted = shouldSortRowsByAnchor
    ? (() => {
        const normalized: Array<{ idx: number; key: string; row: any }> = combinedRows.map((row, idx) => ({
          idx,
          key: normalizeAutoAddAnchorKey((row?.values as any)?.[anchorFieldId]).toLowerCase(),
          row
        }));
        normalized.sort((a, b) => {
          const aKey = a.key;
          const bKey = b.key;
          if (aKey === bKey) return a.idx - b.idx;
          if (!aKey) return 1;
          if (!bKey) return -1;
          return aKey.localeCompare(bKey);
        });
        return normalized.map(entry => entry.row);
      })()
    : combinedRows;
  const changed =
    combinedSorted.length !== currentRows.length || combinedSorted.some((row, idx) => row !== currentRows[idx]);
  return { rows: combinedSorted, changed, contextId, desiredCount: desired.length };
};

export type AutoAddSubgroupAnchorTarget = {
  sub: any;
  subId: string;
  anchorFieldId: string;
};

export type AutoAddSubgroupAnchorAutofillDiagnostic = {
  groupId: string;
  rowId: string | null;
  fieldId: string;
  value: string;
};

export const collectAutoAddSubgroupAnchorTargetsAction = (parentConfig: any): AutoAddSubgroupAnchorTarget[] => {
  const subGroups = Array.isArray(parentConfig?.subGroups) ? parentConfig.subGroups : [];
  return subGroups
    .map((sub: any) => ({
      sub: sub as any,
      subId: resolveSubgroupKey(sub as any),
      anchorFieldId:
        (sub as any)?.anchorFieldId !== undefined && (sub as any)?.anchorFieldId !== null
          ? (sub as any).anchorFieldId.toString()
          : ''
    }))
    .filter((entry: AutoAddSubgroupAnchorTarget) =>
      entry.subId && entry.anchorFieldId && Array.isArray(entry.sub?.fields) && entry.sub.fields.length
    );
};

export const applyAutoAddSubgroupSingleOptionAnchorFillAction = (args: {
  previousLineItems: LineItemState;
  parentGroupId: string;
  subgroupTargets: AutoAddSubgroupAnchorTarget[];
  values: Record<string, FieldValue>;
  subgroupSelectors: Record<string, string>;
  buildOptionSetForLineField: (field: any, groupKey: string) => OptionSet;
  language: LangCode;
}): {
  changed: boolean;
  lineItems: LineItemState;
  diagnostics: AutoAddSubgroupAnchorAutofillDiagnostic[];
} => {
  const parentRows = (args.previousLineItems[args.parentGroupId] || []) as any[];
  if (!parentRows.length || !args.subgroupTargets.length) {
    return { changed: false, lineItems: args.previousLineItems, diagnostics: [] };
  }

  let next: any = args.previousLineItems;
  let didChange = false;
  const diagnostics: AutoAddSubgroupAnchorAutofillDiagnostic[] = [];

  args.subgroupTargets.forEach(({ sub, subId, anchorFieldId }) => {
    const anchorField = (sub.fields || []).find((f: any) => f?.id === anchorFieldId);
    if (!anchorField || anchorField.type !== 'CHOICE') return;
    const dependencyIds = resolveAutoAddDependsOnIds(anchorField);
    const subSelectorId =
      sub?.sectionSelector?.id !== undefined && sub?.sectionSelector?.id !== null ? sub.sectionSelector.id.toString() : '';

    parentRows.forEach(parentRow => {
      const subKey = buildSubgroupKey(args.parentGroupId, parentRow.id, subId);
      const subRows = (next[subKey] || args.previousLineItems[subKey] || []) as any[];
      if (!subRows.length) return;

      const optionSetField = args.buildOptionSetForLineField(anchorField, subKey);
      const depVals = dependencyIds.map((dep: string) => {
        const selectorFallback = subSelectorId && dep === subSelectorId ? (args.subgroupSelectors as any)[subKey] : undefined;
        return toDependencyValue(
          (subRows[0]?.values || {})[dep] ??
            (args.values as any)[dep] ??
            (parentRow?.values || {})[dep] ??
            selectorFallback
        );
      });
      const allowed = computeAllowedOptions(anchorField.optionFilter, optionSetField, depVals);
      const localized = buildLocalizedOptions(optionSetField, allowed, args.language, { sort: optionSortFor(anchorField) });
      const uniqueVals = Array.from(new Set(localized.map(opt => opt.value).filter(Boolean)));
      if (uniqueVals.length !== 1) return;
      const only = uniqueVals[0];

      let changedRows: any[] | null = null;
      subRows.forEach((subRow, idx) => {
        const cur = normalizeAutoAddAnchorKey((subRow?.values || {})[anchorFieldId]);
        if (cur) return;
        if (!changedRows) changedRows = subRows.map(r => ({ ...r, values: { ...(r.values || {}) } }));
        (changedRows[idx].values as any)[anchorFieldId] = only;
        didChange = true;
        diagnostics.push({
          groupId: subKey,
          rowId: subRow?.id || null,
          fieldId: anchorFieldId,
          value: only
        });
      });
      if (changedRows) {
        if (next === args.previousLineItems) next = { ...args.previousLineItems };
        next[subKey] = changedRows;
      }
    });
  });

  if (!didChange || next === args.previousLineItems) {
    return { changed: false, lineItems: args.previousLineItems, diagnostics: [] };
  }
  return { changed: true, lineItems: next as LineItemState, diagnostics };
};
