import { buildLocalizedOptions, computeAllowedOptions, toDependencyValue } from '../../../../core';
import type { FieldValue, LangCode, OptionSet } from '../../../../types';
import {
  ROW_SOURCE_AUTO,
  ROW_SOURCE_KEY,
  parseRowSource
} from '../../../app/lineItems';
import { optionSortFor } from './lineItemPresentation';

const AUTO_CONTEXT_PREFIX = '__autoAddMode__';

export const normalizeAutoAddAnchorKey = (raw: any): string => {
  if (raw === undefined || raw === null) return '';
  if (Array.isArray(raw)) {
    const first = raw[0];
    return first === undefined || first === null ? '' : first.toString().trim();
  }
  return raw.toString().trim();
};

export const resolveAutoAddDependsOnIds = (field: any): string[] => {
  const raw = field?.optionFilter?.dependsOn;
  const ids = Array.isArray(raw) ? raw : raw ? [raw] : [];
  return ids.map((id: any) => (id ?? '').toString().trim()).filter(Boolean);
};

const isValidDependencyValue = (raw: any): boolean => {
  const dep = toDependencyValue(raw as any);
  if (dep === undefined || dep === null) return false;
  if (typeof dep === 'number') return Number.isFinite(dep);
  return dep.toString().trim() !== '';
};

export const resolveAutoAddDesiredRowsAction = (args: {
  groupKey: string;
  anchorField: any;
  dependencyIds: string[];
  getDependencyRaw: (depId: string) => any;
  buildOptionSetForLineField: (field: any, groupKey: string) => OptionSet;
  language: LangCode;
}): { valid: boolean; desired: string[]; depVals: (string | number | null | undefined)[] } => {
  const { groupKey, anchorField, dependencyIds, getDependencyRaw, buildOptionSetForLineField, language } = args;
  const depRawVals = dependencyIds.map(depId => getDependencyRaw(depId));
  const depVals = depRawVals.map(v => toDependencyValue(v as any));
  const valid = dependencyIds.length === 0 || depRawVals.every(isValidDependencyValue);
  if (!valid) return { valid: false, desired: [], depVals };
  const opts = buildOptionSetForLineField(anchorField, groupKey);
  const allowed = computeAllowedOptions(anchorField.optionFilter, opts, depVals);
  const localized = buildLocalizedOptions(opts, allowed, language, { sort: optionSortFor(anchorField) });
  const seen = new Set<string>();
  const desired: string[] = [];
  localized.forEach(opt => {
    const key = (opt?.value ?? '').toString().trim();
    if (!key || seen.has(key)) return;
    seen.add(key);
    desired.push(key);
  });
  return { valid: true, desired, depVals };
};

export const reconcileAutoAddRowsAction = (args: {
  currentRows: any[];
  targetKey: string;
  anchorFieldId: string;
  desired: string[];
  depVals: (string | number | null | undefined)[];
  selectorId?: string;
  selectorValue?: FieldValue;
  createRowId?: (targetKey: string) => string;
}): {
  rows: any[];
  changed: boolean;
  contextId: string;
  desiredCount: number;
} => {
  const { currentRows, targetKey, anchorFieldId, desired, depVals, selectorId, selectorValue } = args;
  const autoPrefix = `${AUTO_CONTEXT_PREFIX}:${targetKey}:`;
  const contextId = `${autoPrefix}${depVals.map(v => (v === undefined || v === null ? '' : v.toString())).join('||')}`;
  const shouldSortRowsByAnchor =
    targetKey === 'MP_MEALS_REQUEST' && anchorFieldId === 'MEAL_TYPE' && Array.isArray(desired) && desired.length > 1;

  const remaining = new Set(desired);

  const nextRows: any[] = [];
  const addedRows: any[] = [];
  currentRows.forEach(row => {
    const isAutoContext =
      (typeof row.effectContextId === 'string' && row.effectContextId.startsWith(autoPrefix)) ||
      parseRowSource((row.values as any)?.[ROW_SOURCE_KEY]) === 'auto';
    if (!isAutoContext) {
      nextRows.push(row);
      return;
    }

    const key = normalizeAutoAddAnchorKey((row.values as any)?.[anchorFieldId]);
    if (!key || !remaining.has(key)) {
      return;
    }
    remaining.delete(key);

    const nextValues: Record<string, FieldValue> = { ...(row.values || {}) };
    let valuesChanged = false;
    if (normalizeAutoAddAnchorKey((nextValues as any)[anchorFieldId]) !== key) {
      nextValues[anchorFieldId] = key;
      valuesChanged = true;
    }
    if (parseRowSource((nextValues as any)[ROW_SOURCE_KEY]) !== 'auto') {
      nextValues[ROW_SOURCE_KEY] = ROW_SOURCE_AUTO;
      valuesChanged = true;
    }
    if (
      selectorId &&
      selectorValue !== undefined &&
      selectorValue !== null &&
      (nextValues as any)[selectorId] === undefined
    ) {
      nextValues[selectorId] = selectorValue;
      valuesChanged = true;
    }

    const metaChanged = row.autoGenerated !== true || row.effectContextId !== contextId;
    if (valuesChanged || metaChanged) {
      nextRows.push({
        ...row,
        values: nextValues,
        autoGenerated: true,
        effectContextId: contextId
      });
    } else {
      nextRows.push(row);
    }
  });

  desired.forEach(key => {
    if (!remaining.has(key)) return;
    remaining.delete(key);
    const nextValues: Record<string, FieldValue> = {
      [anchorFieldId]: key,
      [ROW_SOURCE_KEY]: ROW_SOURCE_AUTO
    };
    if (selectorId && selectorValue !== undefined && selectorValue !== null) {
      nextValues[selectorId] = selectorValue;
    }
    addedRows.unshift({
      id: args.createRowId?.(targetKey) || `${targetKey}_${Math.random().toString(16).slice(2)}`,
      values: nextValues,
      autoGenerated: true,
      effectContextId: contextId
    });
  });

  const combinedRows = addedRows.length ? [...addedRows, ...nextRows] : nextRows;
  const combinedSorted = shouldSortRowsByAnchor
    ? (() => {
        const normalized: Array<{ idx: number; key: string; row: any }> = combinedRows.map((row, idx) => ({
          idx,
          key: normalizeAutoAddAnchorKey((row?.values as any)?.[anchorFieldId]).toLowerCase(),
          row
        }));
        normalized.sort((a, b) => {
          const aKey = a.key;
          const bKey = b.key;
          if (aKey === bKey) return a.idx - b.idx;
          if (!aKey) return 1;
          if (!bKey) return -1;
          return aKey.localeCompare(bKey);
        });
        return normalized.map(entry => entry.row);
      })()
    : combinedRows;
  const changed =
    combinedSorted.length !== currentRows.length || combinedSorted.some((row, idx) => row !== currentRows[idx]);
  return { rows: combinedSorted, changed, contextId, desiredCount: desired.length };
};
