import type { FieldValue, LineItemRowState } from '../../../../types';
import {
  ROW_HIDE_REMOVE_KEY,
  ROW_ID_KEY,
  ROW_PARENT_GROUP_ID_KEY,
  ROW_PARENT_ROW_ID_KEY,
  ROW_SELECTION_EFFECT_ID_KEY,
  ROW_SOURCE_AUTO,
  ROW_SOURCE_KEY
} from '../../../app/lineItems';

const AUTO_ROW_METADATA_KEYS = new Set<string>([
  ROW_ID_KEY,
  ROW_SOURCE_KEY,
  ROW_HIDE_REMOVE_KEY,
  ROW_PARENT_GROUP_ID_KEY,
  ROW_PARENT_ROW_ID_KEY,
  ROW_SELECTION_EFFECT_ID_KEY
]);

/**
 * Owns pure-ish auto-generated line-item row derivation.
 *
 * Keep this boundary free of React and transport calls. Row id generation is
 * injectable for tests; callers that omit it keep the existing random-id behavior.
 */
export const coerceStructuredItems = (payload: any): Record<string, any>[] => {
  if (!payload) return [];
  if (Array.isArray(payload)) {
    return payload.filter(entry => entry && typeof entry === 'object') as Record<string, any>[];
  }
  if (typeof payload === 'string') {
    const trimmed = payload.trim();
    if (!trimmed) return [];
    try {
      const parsed = JSON.parse(trimmed);
      if (Array.isArray(parsed)) {
        return parsed.filter(entry => entry && typeof entry === 'object') as Record<string, any>[];
      }
      if (parsed && typeof parsed === 'object') {
        return [parsed as Record<string, any>];
      }
    } catch {
      return [];
    }
    return [];
  }
  if (payload && typeof payload === 'object') {
    return [payload as Record<string, any>];
  }
  return [];
};

export const coerceNestedLineItemPresetRows = (payload: any): Record<string, FieldValue>[] => {
  if (!payload) return [];
  if (Array.isArray(payload)) {
    return payload.filter(entry => entry && typeof entry === 'object') as Record<string, FieldValue>[];
  }
  if (typeof payload === 'string') {
    const trimmed = payload.trim();
    if (!trimmed) return [];
    try {
      const parsed = JSON.parse(trimmed);
      if (Array.isArray(parsed)) {
        return parsed.filter(entry => entry && typeof entry === 'object') as Record<string, FieldValue>[];
      }
      if (parsed && typeof parsed === 'object') {
        return [parsed as Record<string, FieldValue>];
      }
    } catch {
      return [];
    }
    return [];
  }
  if (typeof payload === 'object') {
    return [payload as Record<string, FieldValue>];
  }
  return [];
};

export const stripAutoRowMetadata = (values: Record<string, FieldValue> | undefined): Record<string, FieldValue> => {
  if (!values || typeof values !== 'object') return {};
  const next: Record<string, FieldValue> = {};
  Object.entries(values).forEach(([key, value]) => {
    if (AUTO_ROW_METADATA_KEYS.has(key)) return;
    next[key] = value;
  });
  return next;
};

const valuesEqual = (left: FieldValue, right: FieldValue): boolean => {
  if (Array.isArray(left) || Array.isArray(right) || (left && typeof left === 'object') || (right && typeof right === 'object')) {
    try {
      return JSON.stringify(left) === JSON.stringify(right);
    } catch {
      return false;
    }
  }
  return left === right;
};

const entryMatchesRow = (entry: Record<string, FieldValue>, row: LineItemRowState | undefined): boolean => {
  if (!row) return false;
  const expected = stripAutoRowMetadata(entry || {});
  const actual = stripAutoRowMetadata((row.values || {}) as Record<string, FieldValue>);
  const expectedKeys = Object.keys(expected);
  const actualKeys = Object.keys(actual);
  if (expectedKeys.length !== actualKeys.length) return false;
  return expectedKeys.every(key => valuesEqual(expected[key], actual[key]));
};

export const childRowsMatchEntries = (
  rows: LineItemRowState[],
  entries: Record<string, FieldValue>[]
): boolean => {
  if (rows.length !== entries.length) return false;
  return rows.every((row, index) => entryMatchesRow(entries[index], row));
};

export const buildAutoGeneratedChildRows = (args: {
  subGroupId: string;
  parentGroupId: string;
  parentRowId: string;
  entries: Record<string, FieldValue>[];
  existingRows?: LineItemRowState[];
  createRowId?: (subGroupId: string, index: number) => string;
}): LineItemRowState[] => {
  const existingRows = Array.isArray(args.existingRows) ? args.existingRows : [];
  const usedIndexes = new Set<number>();
  const createRowId =
    args.createRowId || ((subGroupId: string) => `${subGroupId}_${Math.random().toString(16).slice(2)}`);

  return args.entries.map((entry, index) => {
    let reuseIndex = existingRows.findIndex((row, rowIndex) => !usedIndexes.has(rowIndex) && entryMatchesRow(entry, row));
    if (reuseIndex < 0 && existingRows[index] && !usedIndexes.has(index)) {
      reuseIndex = index;
    }
    const reusableRow = reuseIndex >= 0 ? existingRows[reuseIndex] : null;
    if (reuseIndex >= 0) usedIndexes.add(reuseIndex);
    const reusableId = `${reusableRow?.id || (reusableRow?.values as any)?.[ROW_ID_KEY] || ''}`.trim();
    const childRowId = reusableId || createRowId(args.subGroupId, index);
    const childValues: Record<string, FieldValue> = {
      ...(entry || {}),
      [ROW_ID_KEY]: childRowId,
      [ROW_SOURCE_KEY]: ROW_SOURCE_AUTO,
      [ROW_HIDE_REMOVE_KEY]: true,
      [ROW_PARENT_GROUP_ID_KEY]: args.parentGroupId,
      [ROW_PARENT_ROW_ID_KEY]: args.parentRowId
    };
    return {
      id: childRowId,
      values: childValues,
      parentId: args.parentRowId,
      parentGroupId: args.parentGroupId,
      autoGenerated: true
    } as LineItemRowState;
  });
};
