import { buildLocalizedOptions, toOptionSet } from '../../../../core';
import { resolveLocalizedString } from '../../../../i18n';
import type { FieldValue, LangCode, LineItemRowState } from '../../../../types';
import { coerceStructuredItems } from './autoGeneratedRows';

export type LineItemSortMode = 'alphabetical' | 'source';
export type SourceFirstVisibleSourceRowEntry = {
  sourceRow: Record<string, any>;
  eligibleParents: LineItemRowState[];
};

/**
 * Owns pure line-item display helpers used by row/list renderers.
 *
 * Keep this boundary free of React, DOM state, transport calls, and mutable
 * component state. Components pass raw config/data in and receive display-ready
 * values back.
 */
export const getByPath = (root: any, path: string): any => {
  if (!root || !path) return undefined;
  return path.split('.').reduce((acc: any, segment: string) => {
    if (acc === undefined || acc === null || typeof acc !== 'object') return undefined;
    if (acc[segment] !== undefined) return acc[segment];
    const normalized = segment.toLowerCase();
    const fallbackKey = Object.keys(acc).find(key => key.toLowerCase() === normalized);
    return fallbackKey ? acc[fallbackKey] : undefined;
  }, root);
};

export const normalizeIdValue = (raw: unknown): string => (raw === undefined || raw === null ? '' : String(raw).trim());

export const formatLineItemTotalValue = (total: { value: number; decimalPlaces?: number; pending?: boolean }): string =>
  total.pending ? '' : total.value.toFixed(total.decimalPlaces || 0);

export const hasAvailabilityPairValue = (
  sourceRow: Record<string, any>,
  remainingFieldId: string,
  reservedFieldId: string
): boolean => {
  const hasValue = (raw: unknown): boolean => {
    if (raw === undefined || raw === null) return false;
    if (typeof raw === 'string') return raw.trim().length > 0;
    return true;
  };
  return hasValue(sourceRow?.[remainingFieldId]) || hasValue(sourceRow?.[reservedFieldId]);
};

export const fieldByIdSafe = (fields: any, fieldId: string): any | null => {
  if (!Array.isArray(fields) || !fieldId) return null;
  return fields.find((field: any) => `${field?.id || ''}`.trim() === fieldId) || null;
};

export const optionSortFor = (field: { optionSort?: any } | undefined): LineItemSortMode => {
  const raw = (field as any)?.optionSort;
  const normalized = typeof raw === 'string' ? raw.trim().toLowerCase() : '';
  return normalized === 'source' ? 'source' : 'alphabetical';
};

export const listSortFor = (raw: any): LineItemSortMode => {
  const normalized = typeof raw === 'string' ? raw.trim().toLowerCase() : '';
  return normalized === 'alphabetical' ? 'alphabetical' : 'source';
};

export const sortVisibleTextValues = (values: string[], sortMode: LineItemSortMode): string[] => {
  if (sortMode !== 'alphabetical' || values.length < 2) return values;
  return [...values].sort((left, right) =>
    left.localeCompare(right, undefined, { numeric: true, sensitivity: 'base' })
  );
};

export const resolveCompactPartType = (part: any): string => {
  if (!part || typeof part !== 'object') return 'text';
  const explicit = (part.type || '').toString().trim().toLowerCase();
  if (explicit) return explicit;
  if (part.fieldId || part.sourcePath) return 'field';
  if (Array.isArray(part.sourcePathAlternatives) && part.sourcePathAlternatives.some((value: any) => `${value || ''}`.trim())) {
    return 'field';
  }
  if (Array.isArray(part.fieldIdAlternatives) && part.fieldIdAlternatives.some((value: any) => `${value || ''}`.trim())) {
    return 'field';
  }
  return 'text';
};

const pad2 = (value: number): string => value.toString().padStart(2, '0');

const formatLocalYmd = (date: Date): string =>
  `${date.getFullYear()}-${pad2(date.getMonth() + 1)}-${pad2(date.getDate())}`;

const toDateDisplayValue = (raw: unknown): string => {
  if (raw === undefined || raw === null) return '';
  if (raw instanceof Date) {
    const time = raw.getTime();
    return Number.isNaN(time) ? '' : formatLocalYmd(raw);
  }
  const text = raw.toString().trim();
  if (!text) return '';
  if (/^\d{4}-\d{2}-\d{2}$/.test(text)) return text;
  const isoPrefix = text.match(/^(\d{4}-\d{2}-\d{2})[T\s]/);
  if (isoPrefix) {
    const parsed = new Date(text);
    return Number.isNaN(parsed.getTime()) ? isoPrefix[1] : formatLocalYmd(parsed);
  }
  const dayMonth = text.match(/^(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})$/);
  if (dayMonth) {
    const first = Number(dayMonth[1]);
    const second = Number(dayMonth[2]);
    const year = Number(dayMonth[3]);
    if (!Number.isNaN(first) && !Number.isNaN(second) && !Number.isNaN(year)) {
      let day = first;
      let month = second;
      if (first <= 12 && second > 12) {
        month = first;
        day = second;
      }
      if (month >= 1 && month <= 12 && day >= 1 && day <= 31) {
        return `${year}-${pad2(month)}-${pad2(day)}`;
      }
    }
  }
  const parsed = new Date(text);
  return Number.isNaN(parsed.getTime()) ? '' : formatLocalYmd(parsed);
};

export const resolveSourceFirstAllocationDisplayValue = (args: {
  field: any;
  virtualValues: Record<string, FieldValue>;
  parentValues: Record<string, FieldValue>;
  language: LangCode;
}): string => {
  const { field, virtualValues, parentValues, language } = args;
  if (!field) return '';
  const raw = Object.prototype.hasOwnProperty.call(virtualValues, field.id)
    ? virtualValues[field.id]
    : parentValues[field.id];
  if (raw === undefined || raw === null || raw === '') return '';
  if (field.type === 'DATE') return toDateDisplayValue(raw);
  if (field.type === 'CHOICE' || field.type === 'CHECKBOX') {
    const optionSet = toOptionSet(field);
    const options = buildLocalizedOptions(optionSet, optionSet.en || [], language, {
      sort: optionSortFor(field)
    });
    const rawList = Array.isArray(raw) ? raw : [raw];
    return rawList
      .map(value => `${value ?? ''}`)
      .filter(Boolean)
      .map(value => options.find(option => option.value === value)?.label || value)
      .join(', ');
  }
  return `${raw}`.trim();
};

export const resolveSourceFirstCompactFieldDisplayValue = (args: {
  fieldId: string;
  virtualValues: Record<string, FieldValue>;
  sourceRow: Record<string, any>;
  fieldById: Map<string, any>;
  parentValues: Record<string, FieldValue>;
  language: LangCode;
}): string => {
  const { fieldId, virtualValues, sourceRow, fieldById, parentValues, language } = args;
  const field = fieldById.get(fieldId);
  const display = field
    ? resolveSourceFirstAllocationDisplayValue({ field, virtualValues, parentValues, language })
    : `${virtualValues[fieldId] ?? parentValues[fieldId] ?? ''}`.trim();
  if (display) return display;
  const sourceValue = getByPath(sourceRow, fieldId);
  return sourceValue === undefined || sourceValue === null ? '' : `${sourceValue}`.trim();
};

export const resolveSourceFirstCompactSourceValue = (args: {
  part: any;
  virtualValues: Record<string, FieldValue>;
  sourceRow: Record<string, any>;
  fieldById: Map<string, any>;
  parentValues: Record<string, FieldValue>;
  language: LangCode;
}): string => {
  const { part, virtualValues, sourceRow, fieldById, parentValues, language } = args;
  const sourcePathCandidates = [
    `${part?.sourcePath || ''}`.trim(),
    ...(Array.isArray(part?.sourcePathAlternatives)
      ? part.sourcePathAlternatives.map((value: any) => `${value || ''}`.trim()).filter(Boolean)
      : [])
  ].filter(Boolean);
  for (const candidate of sourcePathCandidates) {
    const sourceValue = getByPath(sourceRow, candidate);
    if (sourceValue !== undefined && sourceValue !== null && `${sourceValue}`.trim() !== '') {
      return `${sourceValue}`.trim();
    }
    if (!candidate.includes('.')) {
      const fallbackDisplay = resolveSourceFirstCompactFieldDisplayValue({
        fieldId: candidate,
        virtualValues,
        sourceRow,
        fieldById,
        parentValues,
        language
      });
      if (fallbackDisplay) return fallbackDisplay;
    }
  }

  const fieldIdCandidates = [
    `${part?.fieldId || ''}`.trim(),
    ...(Array.isArray(part?.fieldIdAlternatives)
      ? part.fieldIdAlternatives.map((value: any) => `${value || ''}`.trim()).filter(Boolean)
      : [])
  ].filter(Boolean);
  for (const candidate of fieldIdCandidates) {
    const display = resolveSourceFirstCompactFieldDisplayValue({
      fieldId: candidate,
      virtualValues,
      sourceRow,
      fieldById,
      parentValues,
      language
    });
    if (display) return display;
  }
  return '';
};

export const resolveSourceFirstCompactTextParts = (args: {
  parts: any[];
  virtualValues: Record<string, FieldValue>;
  sourceRow: Record<string, any>;
  fieldById: Map<string, any>;
  parentValues: Record<string, FieldValue>;
  language: LangCode;
}): string => {
  const { parts, virtualValues, sourceRow, fieldById, parentValues, language } = args;
  return parts
    .map((part: any) => {
      if (!part || typeof part !== 'object') return '';
      const partType = resolveCompactPartType(part);
      if (partType === 'text') {
        return resolveLocalizedString(part.text, language, '');
      }
      if (partType === 'sourcelistsummary') {
        const entries = coerceStructuredItems(getByPath(sourceRow, `${part.sourcePath || ''}`.trim()));
        if (!entries.length) return '';
        const summaryFieldId = `${part.summaryFieldId || part.fieldId || ''}`.trim();
        const separator = resolveLocalizedString(part.separator, language, ', ') || ', ';
        const sortMode = listSortFor(part.sort);
        const values = entries
          .map(entry => (summaryFieldId ? getByPath(entry, summaryFieldId) : entry))
          .map(value => `${value ?? ''}`.trim())
          .filter(Boolean);
        const normalized = part.unique === false ? values : Array.from(new Set(values));
        return sortVisibleTextValues(normalized, sortMode).join(separator);
      }
      const display = resolveSourceFirstCompactSourceValue({
        part,
        virtualValues,
        sourceRow,
        fieldById,
        parentValues,
        language
      });
      const fieldId = `${part.fieldId || ''}`.trim();
      if (!display && !fieldId) return '';
      const suffix = part.suffix
        ? resolveLocalizedString(part.suffix, language, '')
        : part.suffixFieldId
          ? (() => {
              const suffixFieldId = `${part.suffixFieldId || ''}`.trim();
              const suffixField = suffixFieldId ? fieldById.get(suffixFieldId) : null;
              return suffixField
                ? resolveSourceFirstAllocationDisplayValue({
                    field: suffixField,
                    virtualValues,
                    parentValues,
                    language
                  })
                : `${virtualValues[suffixFieldId] ?? parentValues[suffixFieldId] ?? ''}`.trim();
            })()
          : '';
      return [display, suffix].filter(Boolean).join(' ').trim();
    })
    .filter(Boolean)
    .join('');
};

export const resolveSourceFirstSortLabel = (args: {
  entry: SourceFirstVisibleSourceRowEntry;
  config: any;
  compactHeadlineRows: any[];
  fieldById: Map<string, any>;
  language: LangCode;
  buildVirtualValues: (entry: {
    sourceRow: Record<string, any>;
    parentRow?: LineItemRowState;
  }) => Record<string, FieldValue>;
  matchesRule: (entry: {
    rule: any;
    virtualValues: Record<string, FieldValue>;
    parentValues: Record<string, FieldValue>;
  }) => boolean;
}): string => {
  const sourceKeyFieldId = `${args.config?.rowKeyFieldId || ''}`.trim();
  const sourceKey = sourceKeyFieldId ? `${args.entry.sourceRow?.[sourceKeyFieldId] ?? ''}`.trim() : '';
  const anchorParentRow = args.entry.eligibleParents[0];
  const parentValues = (anchorParentRow?.values || {}) as Record<string, FieldValue>;
  const headlineVirtualValues = args.buildVirtualValues({
    sourceRow: args.entry.sourceRow,
    parentRow: anchorParentRow
  });
  const headlineRule = (Array.isArray(args.compactHeadlineRows) ? args.compactHeadlineRows : []).find(rule =>
    args.matchesRule({ rule, virtualValues: headlineVirtualValues, parentValues })
  );
  const headlineText = headlineRule
    ? resolveSourceFirstCompactTextParts({
        parts: Array.isArray(headlineRule.parts) ? headlineRule.parts : [],
        virtualValues: headlineVirtualValues,
        sourceRow: args.entry.sourceRow,
        fieldById: args.fieldById,
        parentValues,
        language: args.language
      })
    : '';
  return (headlineText || sourceKey).trim().toLowerCase();
};

export const sortSourceFirstVisibleSourceRows = (args: {
  rows: SourceFirstVisibleSourceRowEntry[];
  sortMode: LineItemSortMode;
  config: any;
  compactHeadlineRows: any[];
  fieldById: Map<string, any>;
  language: LangCode;
  buildVirtualValues: (entry: {
    sourceRow: Record<string, any>;
    parentRow?: LineItemRowState;
  }) => Record<string, FieldValue>;
  matchesRule: (entry: {
    rule: any;
    virtualValues: Record<string, FieldValue>;
    parentValues: Record<string, FieldValue>;
  }) => boolean;
}): SourceFirstVisibleSourceRowEntry[] => {
  if (args.sortMode !== 'alphabetical') return args.rows;
  return [...args.rows].sort((left, right) =>
    resolveSourceFirstSortLabel({ ...args, entry: left }).localeCompare(
      resolveSourceFirstSortLabel({ ...args, entry: right }),
      undefined,
      {
        numeric: true,
        sensitivity: 'base'
      }
    )
  );
};
