import {
  reconcileAutoAddRowsAction,
  resolveAutoAddDependsOnIds,
  resolveAutoAddDesiredRowsAction
} from '../../../src/web/react/features/lineItems/domain/autoAddModeRows';
import {
  ROW_SOURCE_AUTO,
  ROW_SOURCE_KEY
} from '../../../src/web/react/app/lineItems';

describe('auto add mode row domain', () => {
  test('resolves dependency ids and desired rows from allowed options', () => {
    const anchorField = {
      id: 'MEAL_TYPE',
      optionFilter: { dependsOn: 'DIET' }
    };

    expect(resolveAutoAddDependsOnIds(anchorField)).toEqual(['DIET']);

    const result = resolveAutoAddDesiredRowsAction({
      groupKey: 'MP_MEALS_REQUEST',
      anchorField,
      dependencyIds: ['DIET'],
      getDependencyRaw: () => 'vegetarian',
      buildOptionSetForLineField: () => ({
        en: ['soup', 'soup', 'salad'],
        fr: [],
        nl: []
      }),
      language: 'en'
    });

    expect(result).toEqual({
      valid: true,
      desired: ['salad', 'soup'],
      depVals: ['vegetarian']
    });
  });

  test('reconciles generated auto rows while preserving manual rows', () => {
    const result = reconcileAutoAddRowsAction({
      currentRows: [
        { id: 'manual1', values: { MEAL_TYPE: 'manual' } },
        { id: 'autoSoup', values: { MEAL_TYPE: 'soup', [ROW_SOURCE_KEY]: ROW_SOURCE_AUTO } },
        { id: 'autoOld', values: { MEAL_TYPE: 'old', [ROW_SOURCE_KEY]: ROW_SOURCE_AUTO } }
      ],
      targetKey: 'MEALS',
      anchorFieldId: 'MEAL_TYPE',
      desired: ['salad', 'soup'],
      depVals: ['vegetarian'],
      selectorId: 'SECTION',
      selectorValue: 'lunch',
      createRowId: () => 'autoSalad'
    });

    expect(result.changed).toBe(true);
    expect(result.contextId).toBe('__autoAddMode__:MEALS:vegetarian');
    expect(result.rows.map(row => row.id)).toEqual(['autoSalad', 'manual1', 'autoSoup']);
    expect(result.rows[0]).toMatchObject({
      id: 'autoSalad',
      values: {
        MEAL_TYPE: 'salad',
        SECTION: 'lunch',
        [ROW_SOURCE_KEY]: ROW_SOURCE_AUTO
      },
      autoGenerated: true,
      effectContextId: result.contextId
    });
    expect(result.rows[2]).toMatchObject({
      id: 'autoSoup',
      autoGenerated: true,
      effectContextId: result.contextId
    });
  });
});
