import {
  buildAutoGeneratedChildRows,
  childRowsMatchEntries,
  coerceNestedLineItemPresetRows,
  coerceStructuredItems,
  stripAutoRowMetadata
} from '../../../src/web/react/features/lineItems/domain/autoGeneratedRows';
import {
  ROW_HIDE_REMOVE_KEY,
  ROW_ID_KEY,
  ROW_PARENT_GROUP_ID_KEY,
  ROW_PARENT_ROW_ID_KEY,
  ROW_SELECTION_EFFECT_ID_KEY,
  ROW_SOURCE_AUTO,
  ROW_SOURCE_KEY
} from '../../../src/web/react/app/lineItems';

describe('lineItem auto-generated row domain', () => {
  test('coerces structured payloads from arrays, objects, and JSON strings', () => {
    expect(coerceStructuredItems([{ id: 1 }, null, 'bad', { id: 2 }])).toEqual([{ id: 1 }, { id: 2 }]);
    expect(coerceStructuredItems('{"id":1}')).toEqual([{ id: 1 }]);
    expect(coerceStructuredItems('[{"id":1},0,{"id":2}]')).toEqual([{ id: 1 }, { id: 2 }]);
    expect(coerceStructuredItems('not-json')).toEqual([]);
  });

  test('coerces nested row preset payloads', () => {
    expect(coerceNestedLineItemPresetRows({ meal: 'Standard' })).toEqual([{ meal: 'Standard' }]);
    expect(coerceNestedLineItemPresetRows('[{"meal":"Standard"}]')).toEqual([{ meal: 'Standard' }]);
    expect(coerceNestedLineItemPresetRows('')).toEqual([]);
  });

  test('strips auto row metadata before comparing derived rows', () => {
    const values: any = {
      meal: 'Standard',
      [ROW_ID_KEY]: 'r1',
      [ROW_SOURCE_KEY]: ROW_SOURCE_AUTO,
      [ROW_HIDE_REMOVE_KEY]: true,
      [ROW_PARENT_GROUP_ID_KEY]: 'parent',
      [ROW_PARENT_ROW_ID_KEY]: 'p1',
      [ROW_SELECTION_EFFECT_ID_KEY]: 'effect-1'
    };

    expect(stripAutoRowMetadata(values)).toEqual({ meal: 'Standard' });
    expect(
      childRowsMatchEntries(
        [{ id: 'r1', values }],
        [{ meal: 'Standard' }]
      )
    ).toBe(true);
  });

  test('reuses matching row ids and creates deterministic ids when injected', () => {
    const rows = buildAutoGeneratedChildRows({
      subGroupId: 'ING',
      parentGroupId: 'MEALS',
      parentRowId: 'meal_1',
      entries: [{ ingredient: 'rice' }, { ingredient: 'beans' }],
      existingRows: [{ id: 'existing_1', values: { ingredient: 'rice' } }],
      createRowId: (_subGroupId, index) => `created_${index}`
    });

    expect(rows.map(row => row.id)).toEqual(['existing_1', 'created_1']);
    expect(rows[0].autoGenerated).toBe(true);
    expect(rows[1].values).toMatchObject({
      ingredient: 'beans',
      [ROW_ID_KEY]: 'created_1',
      [ROW_SOURCE_KEY]: ROW_SOURCE_AUTO,
      [ROW_HIDE_REMOVE_KEY]: true,
      [ROW_PARENT_GROUP_ID_KEY]: 'MEALS',
      [ROW_PARENT_ROW_ID_KEY]: 'meal_1'
    });
  });
});
