import { resolveRowDisclaimerText } from '../../../src/web/react/components/form/utils';

describe('rowDisclaimer', () => {
  it('returns empty string when not configured', () => {
    const out = resolveRowDisclaimerText({
      ui: undefined as any,
      language: 'en' as any,
      rowValues: {}
    });
    expect(out).toBe('');
  });

  it('supports simple template interpolation and rowSource detection', () => {
    const out = resolveRowDisclaimerText({
      ui: { rowDisclaimer: { en: 'Source={{__ckRowSource}}' } } as any,
      language: 'en' as any,
      rowValues: { __ckRowSource: 'auto' } as any
    });
    expect(out).toBe('Source=auto');
  });

  it('supports conditional cases and placeholders', () => {
    const ui: any = {
      rowDisclaimer: {
        cases: [
          { when: { fieldId: '__ckRowSource', equals: 'auto' }, text: { en: 'Auto: {{ITEM}}' } },
          { when: { fieldId: '__ckRowSource', equals: 'manual' }, text: { en: 'Manual: {{ITEM}}' } }
        ]
      }
    };

    const a = resolveRowDisclaimerText({
      ui,
      language: 'en' as any,
      rowValues: { __ckRowSource: 'auto', ITEM: 'Tomatoes' } as any
    });
    expect(a).toBe('Auto: Tomatoes');

    const b = resolveRowDisclaimerText({
      ui,
      language: 'en' as any,
      rowValues: { __ckRowSource: 'manual', ITEM: 'Tomatoes' } as any
    });
    expect(b).toBe('Manual: Tomatoes');
  });

  it('computes __ckRowSourceLabel and falls back to autoGenerated when __ckRowSource is missing', () => {
    const out = resolveRowDisclaimerText({
      ui: { rowDisclaimer: { en: '{{__ckRowSourceLabel}} row' } } as any,
      language: 'en' as any,
      rowValues: { ITEM: 'X' } as any,
      autoGenerated: true
    });
    expect(out).toBe('Auto row');
  });
});


