import { resolveRowDisclaimerText } from '../../../src/web/react/components/form/utils';

describe('rowDisclaimer', () => {
  it('returns empty string when not configured', () => {
    const out = resolveRowDisclaimerText({
      ui: undefined as any,
      language: 'en' as any,
      rowValues: {}
    });
    expect(out).toBe('');
  });

  it('supports simple template interpolation and rowSource detection', () => {
    const out = resolveRowDisclaimerText({
      ui: { rowDisclaimer: { en: 'Source={{__ckRowSource}}' } } as any,
      language: 'en' as any,
      rowValues: { __ckRowSource: 'auto' } as any
    });
    expect(out).toBe('Source=auto');
  });

  it('supports conditional cases and placeholders', () => {
    const ui: any = {
      rowDisclaimer: {
        cases: [
          { when: { fieldId: '__ckRowSource', equals: 'auto' }, text: { en: 'Auto: {{ITEM}}' } },
          { when: { fieldId: '__ckRowSource', equals: 'manual' }, text: { en: 'Manual: {{ITEM}}' } }
        ]
      }
    };

    const a = resolveRowDisclaimerText({
      ui,
      language: 'en' as any,
      rowValues: { __ckRowSource: 'auto', ITEM: 'Tomatoes' } as any
    });
    expect(a).toBe('Auto: Tomatoes');

    const b = resolveRowDisclaimerText({
      ui,
      language: 'en' as any,
      rowValues: { __ckRowSource: 'manual', ITEM: 'Tomatoes' } as any
    });
    expect(b).toBe('Manual: Tomatoes');
  });

  it('computes __ckRowSourceLabel and falls back to autoGenerated when __ckRowSource is missing', () => {
    const out = resolveRowDisclaimerText({
      ui: { rowDisclaimer: { en: '{{__ckRowSourceLabel}} row' } } as any,
      language: 'en' as any,
      rowValues: { ITEM: 'X' } as any,
      autoGenerated: true
    });
    expect(out).toBe('Auto row');
  });

  it('supports compound when clauses and can reference external context (e.g., guided step id)', () => {
    const ui: any = {
      rowDisclaimer: {
        cases: [
          {
            when: {
              all: [
                { fieldId: '__ckSelectionEffectId', equals: 'leftover' },
                { not: { fieldId: '__ckStep', equals: ['foodSafety', 'portioning'] } }
              ]
            },
            text: { en: 'Update Requested portions if required' }
          }
        ]
      }
    };

    const visible = resolveRowDisclaimerText({
      ui,
      language: 'en' as any,
      rowValues: { __ckSelectionEffectId: 'leftover' } as any,
      getValue: (id: string) => (id === '__ckStep' ? ('orderForm' as any) : ('' as any))
    });
    expect(visible).toBe('Update Requested portions if required');

    const hidden = resolveRowDisclaimerText({
      ui,
      language: 'en' as any,
      rowValues: { __ckSelectionEffectId: 'leftover' } as any,
      getValue: (id: string) => (id === '__ckStep' ? ('foodSafety' as any) : ('' as any))
    });
    expect(hidden).toBe('');
  });

  it('treats __ckSelectionEffectId as row-scoped (missing key should not fall back to external context)', () => {
    const ui: any = {
      rowDisclaimer: {
        cases: [{ when: { fieldId: '__ckSelectionEffectId', equals: 'leftover' }, text: { en: 'Leftover row' } }]
      }
    };

    // This simulates a buggy external getter that could return a value from another row.
    const out = resolveRowDisclaimerText({
      ui,
      language: 'en' as any,
      rowValues: { __ckRowSource: 'auto' } as any,
      getValue: (id: string) => (id === '__ckSelectionEffectId' ? ('leftover' as any) : ('' as any))
    });
    expect(out).toBe('');
  });
});


