import {
  applyStepDataSourceNestedPresetNormalizationsAction,
  applyStepDataSourceMatchedOutputRuleAction,
  buildStepDataSourceNestedPresetNormalizationSignatureAction,
  collectStepDataSourceNestedPresetNormalizationsAction,
  resolveDataSourceOutputGroupAction,
  resolveStepDataSourceReservationStateForSourceAction
} from '../../../src/web/react/features/lineItems/domain/stepDataSourceRows';
import {
  ROW_HIDE_REMOVE_KEY,
  ROW_ID_KEY,
  ROW_PARENT_GROUP_ID_KEY,
  ROW_PARENT_ROW_ID_KEY,
  ROW_SELECTION_EFFECT_ID_KEY,
  ROW_SOURCE_AUTO,
  ROW_SOURCE_KEY
} from '../../../src/web/react/app/lineItems';

describe('step data source rows domain', () => {
  test('resolves output subgroup metadata for a parent row', () => {
    const subConfig = { id: 'reservations', fields: [] };

    expect(
      resolveDataSourceOutputGroupAction({
        config: { outputGroupId: 'reservations' },
        groupId: 'meals',
        subGroups: [subConfig],
        parentRowId: 'parent1'
      })
    ).toEqual({
      key: 'meals::parent1::reservations',
      subConfig
    });

    expect(
      resolveDataSourceOutputGroupAction({
        config: {},
        groupId: 'meals',
        subGroups: [subConfig],
        parentRowId: 'parent1'
      })
    ).toBeNull();
  });

  test('resolves local and committed reservation state for a source row', () => {
    const config = {
      outputGroupId: 'reservations',
      outputKeyFieldId: 'sourceId',
      selectedFieldId: 'selected',
      quantityFieldId: 'quantity'
    };
    const parentRows: any[] = [{ id: 'parent1', values: {} }, { id: 'parent2', values: {} }];
    const outputFor = (parentRowId: string) => ({ key: `meals::${parentRowId}::reservations`, subConfig: null });
    const quantityFrom = (values: any, selectedFieldId: string, quantityFieldId: string): number =>
      values?.[selectedFieldId] ? Number(values?.[quantityFieldId] || 0) : 0;
    const commonArgs = {
      config,
      sourceKey: 'item1',
      currentParentRowId: 'parent2',
      parentRows,
      lineItems: {
        [outputFor('parent1').key]: [{ id: 'out1', values: { sourceId: 'item1', selected: true, quantity: 2 } }],
        [outputFor('parent2').key]: [{ id: 'out2', values: { sourceId: 'item1', selected: true, quantity: 3 } }]
      },
      stepDataSourceDrafts: {
        'parent2:item1': { selected: true, quantity: 4 }
      },
      reservationCommittedValues: {
        'parent2:item1': { selected: true, quantity: 1 }
      },
      buildStepDataSourceDraftKey: (_config: any, parentRowId: string, sourceKey: string) => `${parentRowId}:${sourceKey}`,
      resolveDataSourceOutputGroup: (_config: any, parentRowId: string) => outputFor(parentRowId),
      resolveLocalReservationQuantityForVisibility: (args: any) =>
        quantityFrom(args.draftValues || args.outputValues || args.committedValues, args.selectedFieldId, args.quantityFieldId),
      resolveReservationQuantityFromValues: quantityFrom
    };

    expect(resolveStepDataSourceReservationStateForSourceAction({ ...commonArgs, mode: 'local' })).toEqual({
      totalReservedQuantity: 6,
      currentRowQuantity: 4
    });
    expect(resolveStepDataSourceReservationStateForSourceAction({ ...commonArgs, mode: 'committed' })).toEqual({
      totalReservedQuantity: 3,
      currentRowQuantity: 1
    });
  });

  test('applies a matched output rule with nested child row presets', () => {
    const outputKey = 'meals::parent1::reservations';
    const result = applyStepDataSourceMatchedOutputRuleAction({
      previousLineItems: {},
      nextState: {},
      outputKey,
      outputGroupConfig: { subGroups: [{ id: 'details' }] },
      existingOutputRow: null,
      parentGroupId: 'meals',
      parentRowId: 'parent1',
      outputGroupId: 'reservations',
      outputKeyFieldId: 'sourceId',
      sourceKey: 'item1',
      quantityFieldId: 'quantity',
      modeFieldId: 'mode',
      rowValues: { quantity: 3, mode: 'portion' },
      preset: { label: 'Soup', details: [{ note: 'nested' }] },
      matchedRule: { id: 'rule1', hideRemoveButton: true },
      createRowId: () => 'out1'
    });

    expect(result[outputKey]).toHaveLength(1);
    expect(result[outputKey][0]).toMatchObject({
      id: 'out1',
      parentId: 'parent1',
      parentGroupId: 'meals'
    });
    expect(result[outputKey][0].values).toEqual({
      quantity: 3,
      mode: 'portion',
      label: 'Soup',
      [ROW_ID_KEY]: 'out1',
      [ROW_SOURCE_KEY]: ROW_SOURCE_AUTO,
      [ROW_PARENT_GROUP_ID_KEY]: 'meals',
      [ROW_PARENT_ROW_ID_KEY]: 'parent1',
      [ROW_HIDE_REMOVE_KEY]: true,
      [ROW_SELECTION_EFFECT_ID_KEY]: 'rule1',
      sourceId: 'item1'
    });
    expect(result[outputKey][0].values).not.toHaveProperty('details');

    const childKey = `${outputKey}::out1::details`;
    expect(result[childKey]).toHaveLength(1);
    expect(result[childKey][0]).toMatchObject({
      parentId: 'out1',
      parentGroupId: outputKey,
      autoGenerated: true
    });
    expect(result[childKey][0].values).toMatchObject({
      note: 'nested',
      [ROW_SOURCE_KEY]: ROW_SOURCE_AUTO,
      [ROW_HIDE_REMOVE_KEY]: true,
      [ROW_PARENT_GROUP_ID_KEY]: outputKey,
      [ROW_PARENT_ROW_ID_KEY]: 'out1'
    });
  });

  test('returns the previous line-item state when a matched output rule is unchanged', () => {
    const outputKey = 'meals::parent1::reservations';
    const previousLineItems: any = {
      [outputKey]: [
        {
          id: 'out1',
          parentId: 'parent1',
          parentGroupId: 'meals',
          values: {
            quantity: 3,
            mode: 'portion',
            label: 'Soup',
            [ROW_ID_KEY]: 'out1',
            [ROW_SOURCE_KEY]: ROW_SOURCE_AUTO,
            [ROW_PARENT_GROUP_ID_KEY]: 'meals',
            [ROW_PARENT_ROW_ID_KEY]: 'parent1',
            [ROW_SELECTION_EFFECT_ID_KEY]: 'rule1',
            sourceId: 'item1'
          }
        }
      ]
    };

    const result = applyStepDataSourceMatchedOutputRuleAction({
      previousLineItems,
      nextState: previousLineItems,
      outputKey,
      existingOutputRow: previousLineItems[outputKey][0],
      parentGroupId: 'meals',
      parentRowId: 'parent1',
      outputGroupId: 'reservations',
      outputKeyFieldId: 'sourceId',
      sourceKey: 'item1',
      quantityFieldId: 'quantity',
      modeFieldId: 'mode',
      rowValues: { quantity: 3, mode: 'portion' },
      preset: { label: 'Soup' },
      matchedRule: { id: 'rule1' }
    });

    expect(result).toBe(previousLineItems);
  });

  test('collects and applies nested preset normalizations for existing output rows', () => {
    const outputKey = 'meals::parent1::reservations';
    const lineItems = {
      [outputKey]: [{ id: 'out1', values: { sourceId: 'item1', quantity: 1 } }]
    };
    const pending = collectStepDataSourceNestedPresetNormalizationsAction({
      activeStepDataSourceRows: [
        {
          rowKeyFieldId: 'sourceId',
          outputKeyFieldId: 'sourceId',
          quantityFieldId: 'quantity',
          outputRules: [{ id: 'rule1', preset: { label: 'Soup', details: [{ note: 'nested' }] } }]
        }
      ],
      parentRows: [{ id: 'parent1', values: {} }],
      lineItems,
      rootGroupId: 'meals',
      stepDataSourceDrafts: {},
      resolveDataSourceOutputGroup: () => ({ key: outputKey, subConfig: null }),
      resolveStepDataSourceRowsForParent: () => [{ sourceId: 'item1' }],
      buildStepDataSourceDraftKey: (_config: any, parentRowId: string, sourceKey: string) => `${parentRowId}:${sourceKey}`,
      buildVirtualDataSourceRowValues: () => ({ sourceId: 'item1', quantity: 2 }),
      matchesWhenClause: () => true,
      resolveVirtualRowWhenContext: args => args,
      resolveVirtualPreset: preset => preset,
      resolveRowFlowGroupConfig: () => ({ config: { subGroups: [{ id: 'details' }] } })
    });

    expect(buildStepDataSourceNestedPresetNormalizationSignatureAction(pending)).toBe(`${outputKey}::out1::details::1`);

    const nextLineItems = applyStepDataSourceNestedPresetNormalizationsAction({
      previousLineItems: lineItems,
      pending
    });
    expect(nextLineItems[outputKey][0].values).toEqual({
      sourceId: 'item1',
      quantity: 2,
      label: 'Soup',
      [ROW_ID_KEY]: 'out1',
      [ROW_SOURCE_KEY]: ROW_SOURCE_AUTO,
      [ROW_PARENT_GROUP_ID_KEY]: 'meals',
      [ROW_PARENT_ROW_ID_KEY]: 'parent1',
      [ROW_SELECTION_EFFECT_ID_KEY]: 'rule1'
    });
    expect(nextLineItems[outputKey][0].values).not.toHaveProperty('details');

    const childKey = `${outputKey}::out1::details`;
    expect(nextLineItems[childKey]).toHaveLength(1);
    expect(nextLineItems[childKey][0].values).toMatchObject({
      note: 'nested',
      [ROW_SOURCE_KEY]: ROW_SOURCE_AUTO,
      [ROW_HIDE_REMOVE_KEY]: true,
      [ROW_PARENT_GROUP_ID_KEY]: outputKey,
      [ROW_PARENT_ROW_ID_KEY]: 'out1'
    });
  });
});
