import {
  DedupRule,
  FileUploadConfig,
  ListViewConfig,
  ListViewColumnConfig,
  ListViewFieldColumnConfig,
  ListViewLegendItem,
  ListViewOpenViewConfig,
  ListViewOpenViewTarget,
  ListViewRuleCase,
  ListViewRuleCellStyle,
  ListViewRuleColumnConfig,
  ListViewRuleIcon,
  ListViewRulePredicate,
  ListViewRuleWhen,
  PaginatedResult,
  RecordMetadata,
  LineItemGroupConfig,
  LineItemGroupUiConfig,
  LineItemDedupRule,
  LineItemSelectorConfig,
  LineItemRowState,
  LocalizedString,
  OptionFilter,
  ValueMapConfig,
  ParagraphDisclaimerConfig,
  QuestionGroupConfig,
  SummaryVisibility,
  ValidationRule,
  VisibilityConfig,
  WebFormDefinition,
  WebQuestionDefinition,
  WebFormSubmission
} from '../types';

export type LangCode = 'EN' | 'FR' | 'NL' | string;

export type FieldValue =
  | string
  | number
  | boolean
  | string[]
  | File[]
  | (string | File)[]
  | FileList
  | Record<string, FieldValue>[]
  | null
  | undefined;

export interface LineItemRowState {
  id: string;
  values: Record<string, FieldValue>;
  parentId?: string;
  parentGroupId?: string;
  autoGenerated?: boolean;
  effectContextId?: string;
}

export interface FormState {
  language: LangCode;
  values: Record<string, FieldValue>;
  lineItems: Record<string, LineItemRowState[]>;
  submitting: boolean;
  recordMeta?: RecordMetadata;
}

export interface OptionSet {
  en?: string[];
  fr?: string[];
  nl?: string[];
  tooltips?: Record<string, string>;
  raw?: any[];
  [key: string]: string[] | Record<string, string> | any[] | undefined;
}

export interface ValidationError {
  fieldId: string;
  message: string;
  scope?: 'main' | 'line';
  rowId?: string;
  /**
   * Optional severity marker for rule-driven messages.
   * - error: blocks submission (default)
   * - warning: informational; does not block submission
   */
  level?: 'error' | 'warning';
  /**
   * Optional warning display hint (UI only).
   * - top: show in warnings banner
   * - field: show under the field
   * - both: show in both places
   */
  warningDisplay?: 'top' | 'field' | 'both';
  /**
   * Optional warning view hint (UI only).
   * - edit: show only on the edit (form) view
   * - summary: show only on the summary view
   * - both: show on both views
   */
  warningView?: 'edit' | 'summary' | 'both';
}

export interface VisibilityContext {
  getValue: (fieldId: string) => FieldValue;
  getLineValue?: (rowId: string, fieldId: string) => FieldValue;
  getLineItems?: (groupId: string) => LineItemRowState[];
}

export interface FilterContext {
  getDependencyValues: (dependsOn: string | string[]) => (string | number | null | undefined)[];
}

export type WhenConfig = ValidationRule['when'];

export type ThenConfig = ValidationRule['then'];

export interface LineItemTotalsInput {
  config: LineItemGroupConfig;
  rows: LineItemRowState[];
}

export {
  WebFormDefinition,
  WebQuestionDefinition,
  LocalizedString,
  OptionFilter,
  ValueMapConfig,
  ParagraphDisclaimerConfig,
  QuestionGroupConfig,
  FileUploadConfig,
  SummaryVisibility,
  VisibilityConfig,
  ValidationRule,
  ListViewConfig,
  ListViewColumnConfig,
  ListViewFieldColumnConfig,
  ListViewLegendItem,
  ListViewOpenViewConfig,
  ListViewOpenViewTarget,
  ListViewRuleCase,
  ListViewRuleCellStyle,
  ListViewRuleColumnConfig,
  ListViewRuleIcon,
  ListViewRulePredicate,
  ListViewRuleWhen,
  LineItemSelectorConfig,
  LineItemGroupUiConfig,
  LineItemDedupRule,
  DedupRule,
  PaginatedResult,
  RecordMetadata,
  WebFormSubmission
};
