import {
  DedupRule,
  ListViewConfig,
  PaginatedResult,
  RecordMetadata,
  LineItemGroupConfig,
  LineItemSelectorConfig,
  LocalizedString,
  OptionFilter,
  QuestionGroupConfig,
  ValidationRule,
  VisibilityConfig,
  WebFormDefinition,
  WebQuestionDefinition,
  WebFormSubmission
} from '../types';

export type LangCode = 'EN' | 'FR' | 'NL' | string;

export type FieldValue =
  | string
  | number
  | boolean
  | string[]
  | File[]
  | (string | File)[]
  | FileList
  | Record<string, FieldValue>[]
  | null
  | undefined;

export interface LineItemRowState {
  id: string;
  values: Record<string, FieldValue>;
  parentId?: string;
  parentGroupId?: string;
  autoGenerated?: boolean;
  effectContextId?: string;
}

export interface FormState {
  language: LangCode;
  values: Record<string, FieldValue>;
  lineItems: Record<string, LineItemRowState[]>;
  submitting: boolean;
  recordMeta?: RecordMetadata;
}

export interface OptionSet {
  en?: string[];
  fr?: string[];
  nl?: string[];
  tooltips?: Record<string, string>;
  raw?: any[];
  [key: string]: string[] | Record<string, string> | any[] | undefined;
}

export interface ValidationError {
  fieldId: string;
  message: string;
  scope?: 'main' | 'line';
  rowId?: string;
}

export interface VisibilityContext {
  getValue: (fieldId: string) => FieldValue;
  getLineValue?: (rowId: string, fieldId: string) => FieldValue;
}

export interface FilterContext {
  getDependencyValues: (dependsOn: string | string[]) => (string | number | null | undefined)[];
}

export type WhenConfig = ValidationRule['when'];

export type ThenConfig = ValidationRule['then'];

export interface LineItemTotalsInput {
  config: LineItemGroupConfig;
  rows: LineItemRowState[];
}

export {
  WebFormDefinition,
  WebQuestionDefinition,
  LocalizedString,
  OptionFilter,
  QuestionGroupConfig,
  VisibilityConfig,
  ValidationRule,
  ListViewConfig,
  LineItemSelectorConfig,
  DedupRule,
  PaginatedResult,
  RecordMetadata,
  WebFormSubmission
};
